### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by 2313Kmsk** [AMPZNetwork/All-The-Forge-8#1]
When you open the GUI, (JEI) to pages 22 and 23, the game crashes. 

**To Reproduce**
Shit E to open inventory and JEI guide
go to page 22-23
4

game will crash

 - OS: Windows
 - All The Forge 8 latest version
 - Platform atlauncher and other launchers
 - Extra mods added by you [none

**Comment by LabsZero** [comment]
Thank you for reporting this issue, I can confirm this has been patched in the upcoming update V0.0.3.
