### ISSUE TITLE
[Feature Request] Missing QOL mods

### ISSUE THREAD

**Issue by HalJordan** [AMPZNetwork/All-The-Forge-8#2]
You're missing many of the *tweaks mods which allow for MAJOR improvements to gameplay such as shift click and drag to swap between inventories, sorting the player's inventory and/or whatever chest is open, etc.

These are staples of modded Minecraft. I'm kinda shocked Mojang/Microsoft haven't done to those what they tried with pistons/ender chests, but until they pull their heads back out into the sunshine and give what is needed rather than what they think everyone wants, such mods should really be the first on the list for any pack being setup.

Quark is here, and is nice, but it's only a first step.

Edit: You're also missing Fast Leaf Decay(or one of it's alternatives).

**Comment by LabsZero** [comment]
Please post any suggestions for our packs here:
https://forums.ampznetwork.com/suggestions/category/17-all-the-forge-8/

Thank you
