### ISSUE TITLE
cant install optifine

### ISSUE THREAD

**Issue by DavidieHD** [AMPZNetwork/All-The-Forge-8#6]
when i install optifine the game doesnt start anymore is optifine deactiveted? i want to install it because my world beginns to lag

**Comment by LabsZero** [comment]
It's not deactivated it may be due to optifine only supporting an older version of Forge.

**Comment by ProNoob135** [comment]
Rubidium and Oculus work well, though with shaders tinkers will break.

**Comment by LabsZero** [comment]
Optifine doesn't officially support the forge version ATF8 is running. That might be why your having issues
