### ISSUE TITLE
Unable to connet to internal IP on local lan due to server.properties setting

### ISSUE THREAD

**Issue by djmixman** [AMPZNetwork/All-The-Forge-8#9]
In the `server.properties` file there in a setting called `prevent-proxy-connections` that should be defaulted to `false`. However, in ATF8 it's set to `true` by default. This was causing some lan-local clients and a one remote client to fail username verification with "Unable to verify username.". As soon as this option was reverted back to false it started working again.

**Comment by LabsZero** [comment]
Fixed in v0.9
